### ISSUE TITLE
ESBMC - data races check error - semaphores

### ISSUE THREAD

**Issue by SanjanaSai94** [esbmc/esbmc#1517]
Hi all,

I am working with the verification of multithreaded applications using ESBMC, specifically utilizing the deadlock and data races check in-built feature of the tool. I recently found an example in C with the data races check where it detects data race despite handling the data race problem using semaphores as seen in the code attached. I have tried the same example with MUTEX and the data race check works fine in that case. Why is the data race condition being detected in the case of semaphores?

Command executed: esbmc rc_ex_sem.c --unwind 2 --no-unwinding-assertions --data-races-check
[rc_ex_sem.docx](https://github.com/esbmc/esbmc/files/13440285/rc_ex_sem.docx)

**Comment by fbrausse** [comment]
```c
#include <stdio.h>
#include <pthread.h>
#include <semaphore.h>
#include <unistd.h>

int count = 0;
sem_t sem; // declare the semaphore

void *increment(void *arg) {
    int i;
    for (i = 0; i < 10; i++) {
        sem_wait(&sem); // decrement the semaphore
        count++;
        sem_post(&sem); // increment the semaphore
    }
    return NULL;
}

int main() {
    pthread_t t1, t2;
    sem_init(&sem, 0, 1); // initialize the semaphore
    pthread_create(&t1, NULL, increment, NULL);
    //sleep(10);
    pthread_create(&t2, NULL, increment, NULL);
    pthread_join(t1, NULL);
    pthread_join(t2, NULL);
    sem_destroy(&sem); // destroy the semaphore
    printf("Count: %d\n", count);
    return 0;
}
```

**Comment by lucasccordeiro** [comment]
@XLiZHI: as discussed, could you please submit a PR that adds the operational models for sem_*?

**Comment by lucasccordeiro** [comment]
@SanjanaSai94: we have just merged this PR https://github.com/esbmc/esbmc/pull/1536.

Please let us know if you still find issues related to the data race check for programs with semaphores.

**Comment by SanjanaSai94** [comment]
Hello @lucasccordeiro,

I checked the same example with the two versions released since last week. The issue still persists. Kindly verify.

I am running the exact code attached earlier with the below simple command for data race check with and without any additional constraints. But the result is the same and data race is still being detected as seen in the attachment.

Commands :

esbmc rc_ex_sem.c --data-races-check
esbmc rc_ex_sem.c --unwind 2 --no-unwinding-assertions --data-races-check
esbmc rc_ex_sem.c  --no-unwinding-assertions --data-races-check

![image](https://github.com/esbmc/esbmc/assets/151738066/6f22073e-d4f0-40cb-9ef7-ac76aab2a776)

Thanks and regards,
Sanjana Sainath

**Comment by XLiZHI** [comment]
Hi @SanjanaSai94 ,

I rechecked the case, and I didn't reproduce it.

ESBMC version: [71ccbbb](https://github.com/esbmc/esbmc/commit/71ccbbb061794d9b0fb5b2384cac1bcfa5257d72).

cmd: `esbmc main.c --unwind 2 --no-unwinding-assertions --data-races-check`

result: 
![`X1Q V8OMQF`C`~Z07@4TRA](https://github.com/esbmc/esbmc/assets/115160284/5af3e291-163b-4af1-9898-32fb182b39c4)

Would you mind confirming the version you're using? The corrected version is https://github.com/esbmc/esbmc/releases/tag/nightly-71ccbbb061794d9b0fb5b2384cac1bcfa5257d72

you can also try using esbmc in the current directory: `./esbmc`.

Thanks

**Comment by SanjanaSai94** [comment]
Hi @XLiZHI,

Thank you for the details. It is working now with the version mentioned. 

Regards,
Sanjana

**Comment by lucasccordeiro** [comment]
@SanjanaSai94: I'm glad to hear that it is working. Please let us know if you find further issues in ESBMC.
