### ISSUE TITLE
witneses.h

### ISSUE THREAD

**Issue by kaled-alshmrany** [esbmc/esbmc#291]
ESBMC could not reach the input "non-deterministic input" if this input is located in the line-number higher than 13,372. For example, in the program "problem07-lable10.c'' in the benchmarks of Test-Comp 2020, ESBMC could not perform well. This issue happened since the variable responsible for storing the line number in the ESBMC could not approximately store a value higher than approximately 13,372 In the "problem07-lable10.c'' program. The non-deterministic variable is located in the line 215,423, which caused the ESBMC to be unable to produce counterexamples for these goals. 

In my opinion, this problem is related to the "witnesses.h" file where you define the variable as "unsigned short int start_line."

To give more clarity about the issue, please take a look at this video:
https://www.dropbox.com/s/hwkxdqc00v6mn7i/explanation_1.mp4?dl=0
and
https://www.dropbox.com/s/cbjqw9hucpmro43/explanation_2.mp4?dl=0

The link for the program "problem07-lable10.c":
https://github.com/sosy-lab/sv-benchmarks/blob/testcomp20/c/eca-rers2012/Problem07_label10.c

**Comment by mikhailramalho** [comment]
I think you're right, the number `215414` is `11 01001001 01110110` (18 bits long), but if we try to fit it into 16 bits, the two MSB are ignored and we end up with `01001001 01110110` or `18806`.

It should be fairly simple to fix it since we have `BigInt`s in ESBMC, that can hold numbers of arbitraty sizes. I'll send a path latter today.

**Comment by mikhailramalho** [comment]
Fixed by PR #294

**Comment by lucasccordeiro** [comment]
@mikhailramalho: @kaled-alshmrany told me that this issue still happens. So, I'm reopening it.

@kaled-alshmrany: could you please provide us with further information about the problem?

**Comment by lucasccordeiro** [comment]
This issue is no longer valid.
