### ISSUE TITLE
ESBMC reports oversized field offset

### ISSUE THREAD

**Issue by lucasccordeiro** [esbmc/esbmc#448]
ESBMC reports that this C program contains a deference failure, in particular, oversized field offset, which seems to be wrong. This issue requires further investigation.

@mikhailramalho and @rafaelsamenezes: do you have any thoughts?

```
#include <stdbool.h>
#include <stdint.h>


typedef struct str1_t {
    unsigned int field1 : 16;
    unsigned int field2 : 8;
    uint8_t field3[59];
} str1_t;


typedef struct str2_t {
    str1_t field1;
    uint32_t field2;
    uint64_t field3;
    uint32_t field4;
    uint32_t field5[4];
    uint32_t field6;
} str2_t;


int main(void) {

    str2_t var_data;
    str2_t *var_data_p = &var_data;
    uint64_t var_offset[1000]; // = 0xdeadbeef;
    
    for (uint16_t i=0; i < sizeof(str1_t)/sizeof(uint64_t); i++) {
        ((uint64_t *)&var_data_p->field1)[i] = ((uint64_t *)var_offset)[i];
    }
   return 0; 
}
```

**Comment by rafaelsamenezes** [comment]
~I was not able to replicate this issue. Which branch and options are you using?~

This issue doesn't happen on the latest version of ESBMC. It has the following problem:

```
 ../src/pointer-analysis/dereference.cpp:1742: expr2tc* dereferencet::extract_bytes_from_array(const expr2tc&, unsigned int, const expr2tc&): Assertion `subtype->get_width() == 8 && "Can only extract bytes for stitching from byte array"' failed.
```

**Comment by lucasccordeiro** [comment]
ucode branch 

Just run ESBMC file.c

**Comment by lucasccordeiro** [comment]
@shmarovfedor: Should this issue be fixed by https://github.com/esbmc/esbmc/pull/590?

**Comment by shmarovfedor** [comment]
@lucasccordeiro, I don't think so. I'm still getting the same error message as @rafaelsamenezes : 
```
Assertion failed: (subtype->get_width() == 8 && "Can only extract bytes for stitching from byte array"), function extract_bytes_from_array, file dereference.cpp, line 1799.
```
I will look into this issue.

**Comment by lucasccordeiro** [comment]
@shmarovfedor: Can I ask you whether you have had a chance to look at this issue related to bitfield?
