### ISSUE TITLE
--smt-formula-only flag causes crash, --smt-formula-too doesn't print SMT

### ISSUE THREAD

**Issue by will-leeson** [esbmc/esbmc#646]
When running with the --smt-formula-only flag, esbmc crashes. Using the ESBMC-Linux.sh install, it dumps the core. Building from master crashes silently (No core dump but $? returns 127).

Using the --smt-formula-too flag, esbmc finishes verification, but it doesn't print the SMT program.

I've replicated this on several C programs from sv-benchmarks with both the script install and building from master.

**Comment by mikhailramalho** [comment]
The latter is an easy fix: there is an extra space in `options.cpp` when defining the flag:
```
    {"smt-formula-too ", // <- extra space at the end
     NULL,
     "show SMT formula (not supported by all solvers), and verify"},
```

**Comment by will-leeson** [comment]
I'm not sure that fixes it. I removed the extra space and rebuilt. The SMT formula is still not printed

**Comment by will-leeson** [comment]
It appears the issue is that I needed to specify the output file also. In the SV-Comp-22 version of ESBMC it prints to terminal if there isn't the output flag isn't specified. With the output flag `echo $?` still returns 127. Not sure if this is intended behavior, but it would be nice if --smt-formula-only and --smt-formula-too either dumped to stdout or required the output flag

**Comment by rafaelsamenezes** [comment]
@will-leeson, just add `--verbosity 9`, it should solve it. The issue is that although we should be printing this as STATUS message, it is being printed as a DEBUG. The example below worked fine for me with `esbmc --smt-formula-only file.c --verbosity 9`

```c
int main() {
    int a;
    int b;
    int c = 42;
    int d;
    d = 20;
    assert(a + b + d == 42);
}
```

I wasn't able to replicate the crash though. Could you provide your input?

Edit: if your input is private, try reducing it: https://github.com/esbmc/esbmc/wiki/Reducing-C-Programs

Edit2: It seems that the behaviour is not stable throughout the solvers

**Comment by will-leeson** [comment]
Which smt solver is your install using by default? It seems to depend on the solver. It works for Z3 and mathsat, but boolector and bitwuzla seem to still fail. I was able to get it to print to file by editing dump_smt() in bitwuzla_conv.cpp (line 825). I changed line 827 from `FILE *f = msg.get_temp_file();` to  `FILE *f = fopen("myFile.smt2", "w");` I didn't look at boolector though.

`./esbmc --verbosity 9 --smt-formula-only --boolector file.c` and `./esbmc --verbosity 9 --smt-formula-only --boolector --output=file.smt2 file.c`both fail to output formulas and abort after "Encoding solver time:" is printed

**Comment by rafaelsamenezes** [comment]
> Which smt solver is your install using by default?

If available Boolector.

> both fail to output formulas and abort after "Encoding solver time:" is printed

That's odd, It seems fine to me. Could you give me:

- The git hash you are running: `--git-hash` on ESBMC
- OS version and arch
- Boolector version/branch you are using
- cmake output

That may help me to replicate.

Edit: I had the same behaviour that you described if the flag `output` is used

**Comment by will-leeson** [comment]
- Hash: b8b738f3f4cd0cd1fce1b437618d86429b78dab9
- OS and arch: Ubuntu 20.04 x86_64
- Boolector version/branch: 3.2.1 (I used the command in the BUILDING.md file)
- Cmake Output: Do you want the entire output or a specific portion? I don't see any errors besides a dev warning about target_make_policy

**Comment by will-leeson** [comment]
I rebuilt the project from scratch. Cmake by default was using GCC-9 and I noticed there was some error being output. I rebuilt with the downloaded version of clang (Clang-11) using `export CC=$PWD/../../clang11/bin/clang` `export CXX=$PWD/../../clang11/bin/clang++` and now things appear to be working the same as you.

**Comment by fbrausse** [comment]
gcc-9 has had issues before, maybe we should error in the CMake phase? https://github.com/esbmc/esbmc/blob/82e95614d4ddd44de7f9d141d7a90d0461a27b56/scripts/cmake/Irep2Optimization.cmake#L5

**Comment by will-leeson** [comment]
This was the message that triggered me to switch to clang. Unfortunately I didn't see it before. There still appears to be some bug with smt printing, so perhaps not all bad

**Comment by rafaelsamenezes** [comment]
> gcc-9 has had issues before, maybe we should error in the CMake phase? 

This happened during the old precompiled irep2. And if you see the message, the optimization will not run. 

We still have to investigate what is the relation between gcc and the smt-formula flag.

**Comment by lucasccordeiro** [comment]
@will-leeson: @kunjsong01 has fixed some issues recently concerning the `--smt-formula-only`. Can I ask you to try using this flag with the master version?

**Comment by will-leeson** [comment]
I rebuilt the repo from scratch on master. 
`esbmc --smt-formula-only --output=file.smt2 file.c` and `esbmc --smt-formula-only file.c` failed to produce SMT queries, either to STDOUT, STDERR or to a file.
`esbmc --verbosity 9 --smt-formula-only --output=file.smt2 file.c` produced an SMT query to STDOUT, but produced to file.smt2 file. 

Is there something else I should be looking for?

**Comment by kunjsong01** [comment]
It appears that `--smt-formula-only/too` works for Z3, mathsat and CVC solvers, but still broken for boolector and bitwuzla.

**Comment by will-leeson** [comment]
CVC seems to be at least partially broken on my build. By this I mean, it is not outputting full queries in SMTLib format. Also, I can only get Z3 to output to file

**Comment by lucasccordeiro** [comment]
Closed via https://github.com/esbmc/esbmc/pull/2743.
